### ISSUE TITLE
504 Exception 

### ISSUE THREAD

**Issue by Grokzen** [dynamist/phabfive#27]
### Environment

* Python version: 3.6
* Phabfive version: Git hash 67399d1

### Steps to Reproduce

1. Setup a phabricator instance
2. Make the instance not accessible or connectable (Shut it down for example)
3. Run `phabfive K32`

```
$ phabfive K32
Traceback (most recent call last):
  File "/home/nn/profile/bin/phabfive", line 11, in <module>
    load_entry_point('phabfive', 'console_scripts', 'phabfive')()
  File "/home/nn/code/phabfive-github/phabfive/cli.py", line 184, in cli_entrypoint
    sys.exit(run(cli_args, sub_args))
  File "/home/nn/code/phabfive-github/phabfive/cli.py", line 139, in run
    p = passphrase.Passphrase()
  File "/home/nn/code/phabfive-github/phabfive/passphrase.py", line 22, in __init__
    super(Passphrase, self).__init__()
  File "/home/nn/code/phabfive-github/phabfive/core.py", line 77, in __init__
    self.verify_connection()
  File "/home/nn/code/phabfive-github/phabfive/core.py", line 83, in verify_connection
    result = self.phab.user.whoami()
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 248, in __call__
    return self._request(**kwargs)
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 314, in _request
    'Bad response status: {0}'.format(response.status)
http.client.HTTPException: Bad response status: 504
```

**Comment by holmboe** [comment]
This was fixed in commit 7bd0855 which added proper error handling for `requests.exceptions.RequestException` in all CLI modules. Network errors (including HTTP 504) are now displayed with a user-friendly message instead of a Python traceback.
