### ISSUE TITLE
Exception timeout in passphrase module

### ISSUE THREAD

**Issue by Grokzen** [dynamist/phabfive#29]
### Environment

* Python version: 3.6
* Phabfive version: 0.1.0

### Steps to Reproduce

```
(phabfive-kOPdHCq0) ~/c/d/phabfive ❯❯❯ PHABFIVE_DEBUG=1 phabfive passphrase K30
INFO:phabfive.controller:Loglevel is: DEBUG
DEBUG:phabfive.controller:Loading configuration defaults
DEBUG:phabfive.controller:Loading configuration file: /etc/phabfive.yaml
DEBUG:phabfive.controller:Loading configuration files: /etc/phabfive.d/*.yaml
DEBUG:phabfive.controller:Loading configuration file: /home/nn/.config/phabfive.yaml
DEBUG:phabfive.controller:Loading configuration files: /home/nn/.config/phabfive.d/*.yaml
DEBUG:phabfive.controller:Loading configuration from environment
DEBUG:phabfive.controller:PHABFIVE_DEBUG ........ 1
DEBUG:phabfive.controller:PHAB_TOKEN ............ cli-y...
DEBUG:phabfive.controller:PHAB_URL .............. https://.../api/
DEBUG:phabfive.controller:Controller for https://....com/api/
Traceback (most recent call last):
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/bin/phabfive", line 11, in <module>
    load_entry_point('phabfive', 'console_scripts', 'phabfive')()
  File "/home/nn/code/phabfive/phabfive/cli.py", line 153, in cli_entrypoint
    sys.exit(run(cli_args, sub_args))
  File "/home/nn/code/phabfive/phabfive/cli.py", line 116, in run
    c = Controller()
  File "/home/nn/code/phabfive/phabfive/controller.py", line 78, in __init__
    self.passphrase = passphrase.Passphrase(self.conf)
  File "/home/nn/code/phabfive/phabfive/passphrase.py", line 23, in __init__
    self.verify_connection()
  File "/home/nn/code/phabfive/phabfive/interface.py", line 17, in verify_connection
    result = self.phab.user.whoami()
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 248, in __call__
    return self._request(**kwargs)
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 308, in _request
    conn.request('POST', path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

```
Traceback (most recent call last):
  File "/home/nn/profile/bin/phabfive", line 11, in <module>
    load_entry_point('phabfive', 'console_scripts', 'phabfive')()
  File "/home/nn/code/phabfive-github/phabfive/cli.py", line 198, in cli_entrypoint
    sys.exit(run(cli_args, sub_args))
  File "/home/nn/code/phabfive-github/phabfive/cli.py", line 152, in run
    p.print_secret(sub_args["<id>"])
  File "/home/nn/code/phabfive-github/phabfive/passphrase.py", line 50, in print_secret
    secret = self.get_secret(ids)
  File "/home/nn/code/phabfive-github/phabfive/passphrase.py", line 34, in get_secret
    response = self.phab.passphrase.query(ids=[ids], needSecrets=1)
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 248, in __call__
    return self._request(**kwargs)
  File "/home/nn/.virtualenvs/phabfive-kOPdHCq0/lib/python3.6/site-packages/phabricator/__init__.py", line 308, in _request
    conn.request('POST', path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:835: The handshake operation timed out
```

### Expected Behavior

Better formatted exception

### Observed Behavior

Bad formatted exception

**Comment by holmboe** [comment]
This was fixed in commit 7bd0855 which added proper error handling for `requests.exceptions.RequestException` in all CLI modules. Timeout errors are now displayed with a user-friendly message instead of a Python traceback.
