### ISSUE TITLE
SSL operation timeout

### ISSUE THREAD

**Issue by Grokzen** [dynamist/phabfive#35]
### Environment

* Python version: 3.6
* Phabfive version: 0.1.0

### Steps to Reproduce

Given the following exception below

```
~ » phabfive passphrase K32                                                                                            mai@maiThinkPad
Traceback (most recent call last):
  File "/home/mai/.virtualenvs/phabfive/bin/phabfive", line 11, in <module>
    load_entry_point('phabfive', 'console_scripts', 'phabfive')()
  File "/home/mai/dynamist/phabfive/phabfive/cli.py", line 278, in cli_entrypoint
    sys.exit(run(cli_args, sub_args))
  File "/home/mai/dynamist/phabfive/phabfive/cli.py", line 170, in run
    p.print_secret(sub_args["<id>"])
  File "/home/mai/dynamist/phabfive/phabfive/passphrase.py", line 59, in print_secret
    secret = self.get_secret(ids)
  File "/home/mai/dynamist/phabfive/phabfive/passphrase.py", line 34, in get_secret
    response = self.phab.passphrase.query(ids=[ids], needSecrets=1)
  File "/home/mai/.virtualenvs/phabfive/lib/python3.6/site-packages/phabricator/__init__.py", line 248, in __call__
    return self._request(**kwargs)
  File "/home/mai/.virtualenvs/phabfive/lib/python3.6/site-packages/phabricator/__init__.py", line 308, in _request
    conn.request('POST', path, body, headers)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1415, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:835: The handshake operation timed out
```

### Expected Behavior

Better formatted exception.

### Observed Behavior

Bad formatted exception printed to enduser

**Comment by holmboe** [comment]
This was fixed in commit 7bd0855 which added proper error handling for `requests.exceptions.RequestException` in all CLI modules. SSL timeout errors are now displayed with a user-friendly message instead of a Python traceback.
